blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime
from django.utils import timezone
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    date_published = models.DateField(default=timezone.now)
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.order_by('date_published')
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<div class="container">
    <h1 class="display-1 text-center fw-bold">Блог</h1>
    <h2 class="display-5 text-center">Содержит блоги в количестве: {{ blogs.count }} штук</h2>
    {% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id %}"><h2 class="text-primary display-3 ">{{ blog.title }}</h2></a>
    <h3 class="text-secondary fw-lighter">{{ blog.date_published|date:'d M Y'|upper }}</h3>
    <p>{{ blog.description|safe|truncatechars:100 }}</p>
    {% endfor %}
    </br>
</div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>{{ blog.title }}</h1>

<h2>--{{ blog.date_published|date:'d F Y' }}--</h2>

<h3>{{ blog.description|safe }}</h3>

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'portfolio/logo.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <title>Мое портфолио</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container container-fluid">
          <a class="navbar-brand nav-link" href="{% url 'blog:all_blogs' %}">
            <img src="{% static 'portfolio/logo.png' %}" alt="Logo" height="24" class="d-inline-block align-text-top">  Keith Flinth
          </a>
      </div>
      <div class="container justify-content-end nav nav-pills">
          <a class="navbar-brand nav-link" href="{% static 'portfolio/resume.pdf' %}">Резюме</a>
          <a class="navbar-brand nav-link" href="/">Портфолио</a>
          <a class="navbar-brand nav-link" href="https://twitter.com/keithflint" target="_blank" >Твиттер</a>
          <a class="navbar-brand nav-link active" href="{% url 'blog:all_blogs' %}">Блог</a>
      </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}



<div class="container position-relative text-center">
    <h1 class="display-2">Моё портфолио</h1>
    <img src="{% static 'portfolio/flinth.jpg' %}" alt="Кейт">
    <span class="placeholder col-12 bg-light"></span>
    <blockquote class="blockquote">
        <p>Кит Чарльз Флинт!!! :) (англ. Keith Charles Flint; 17 сентября 1969, Редбридж, Лондон — 4 марта 2019, Норт-Энд,
            Эссекс, Великобритания) — бывший вокалист и танцор британской электронной группы «The Prodigy».</p>
    </blockquote>
</div>

<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6 text-center">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-4" width="220" height="220">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-4" width="220" height="220" >
    {% endif %}
    <h3 class="text-center">{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>
{% endblock %}